package piano.ui.buttons;

public enum ButtonType {
	BACK, PIANO_UI, LIST_BUTTON, BOX_BUTTON, KEYBOARD_KEY,
	SONG_SELECTION, VIEW_BUTTON, DEMO_BUTTON, PRACTICE_BUTTON,
	EXAM_BUTTON, PRACTICE_LEFT_BUTTON, PRACTICE_RIGHT_BUTTON;
}
